#!/bin/bash

# Exit script on any errors
set -e

usage() {
  cat << USAGE
Usage: $(basename $0) [-fh] [-m MEDIA-DIRECTORY]
This script makes a Docker-based Jellyfin Media Server based out of this
directory by creating the .env file containing the server's configuration.

Options:
  -f                    force overwrite of existing files
  -m MEDIA-DIRECTORY    path to the media (videos, music) to be served
                        by the Jellyfin Media Server
  -h                    display usage information
USAGE
}

# -- MAIN --

# Handle options
while getopts 'm:fh' opt; do
  case "$opt" in
    f)
      force_overwrite=1
      ;;
    m)
      jellyfin_server_media="$OPTARG"
      ;;
    ?|h)
      usage
      exit
      ;;
  esac
done
shift "$(($OPTIND -1))"

echo "Configuring Jellyfin Media Server"
[[ -n "${force_overwrite}" ]] && echo "FORCING overwrite !"

# -- UserID/GroupID for File Permissions--
current_user=$(whoami)
current_uid=$(id -u $current_user)
current_gid=$(id -g $current_user)

# -- Persistent Server Directories --
jellyfin_server_dir="${PWD}/.jellyfin-server"

jellyfin_server_data_dir="${jellyfin_server_dir}/data"
jellyfin_config_dir="${jellyfin_server_data_dir}/config"
jellyfin_cache_dir="${jellyfin_server_data_dir}/cache"

# Create the directories
jellyfin_directories=(
  "${jellyfin_server_dir}"
  "${jellyfin_server_data_dir}"
  "${jellyfin_config_dir}"
  "${jellyfin_cache_dir}"
)

for dir in ${jellyfin_directories[@]}; do
  # non-destructive
  mkdir -p "${dir}"
done

# Set the persistent server media directory
if [[ -z "${jellyfin_server_media}" ]] ; then
  read -p "Please ENTER the full path to your Media: " jellyfin_server_media
fi
# Safely strip off any trailing slashes (macOS-compatible)
while [[ "$jellyfin_server_media" != "${jellyfin_server_media%/}" ]]; do
  jellyfin_server_media="${jellyfin_server_media%/}"
done

if [[ ! -d "${jellyfin_server_media}" ]] ; then
  echo "!!! FYI, currently there is no directory at [${jellyfin_server_media}] !!!"
fi

# Set the persistent Jellyfin server json.config file
jellyfin_config_json_file="${jellyfin_server_dir}/config.json"

# -- Write .env File --
if [[ -n "${force_overwrite}" || ! -f ".env" ]] ; then
  echo -e "\nCreating .env file..."

  cat << EOF > .env
JELLYFIN_UID=${current_uid}
JELLYFIN_GID=${current_gid}
JELLYFIN_CONFIG=${jellyfin_config_dir}
JELLYFIN_CACHE=${jellyfin_cache_dir}
JELLYFIN_MEDIA=${jellyfin_server_media}
JELLYFIN_CONFIG_JSON=${jellyfin_config_json_file}
EOF
fi

echo -e "\nCurrent .env file:"
cat ".env"

# -- Copy Jellyfin config.json File --
if [[ -n "${force_overwrite}" || ! -f "${jellyfin_config_json_file}" ]] ; then
  echo -e "\nCreating JellyFin Configuration file [${jellyfin_config_json_file}]..."
  cp jellyfin.config.json "${jellyfin_config_json_file}"
fi

echo -e "\nCurrent JellyFin Configuration:"
cat "${jellyfin_config_json_file}"

# Output outro message on running the Jellyfin Media Server
cat << OUTRO

------------------------------------------------------------------
USE the following commands to use the Jellyfin Media Server

  ./run-jellyfin     To RUN the Jellyfin Media Server

  ./stop-jellyfin    To STOP the running Jellyfin Media Server
------------------------------------------------------------------

OUTRO
